name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APP_ENV: prod

jobs:
  build:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy container
        run: |
          docker build -t roboshi .
          docker run roboshi {{ env.APP_ENV }}